module.exports = {
  allowedTags: [ 
    'a',
    'article',
    'b',
    'blockquote',
    'br',
    'caption',
    'code',
    'dd',
    'del',
    'details',
    'div',
    'dl',
    'dt',
    'em',
    'figcaption',
    'figure',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'i',
    'img',
    'ins',
    'input',
    'li',
    'meta',
    'ol',
    'p',
    'path',
    'pre',
    's',
    'span',
    'strike',
    'strong',
    'sub',
    'summary',
    'sup',
    'svg',
    'table',
    'tbody',
    'td',
    'th',
    'thead',
    'tr',
    'ul' 
  ],

  allowedAttributes: {
    // Note that some tags are not allowed by default
    '*': ['class', 'align', 'valign', 'title'],
    a: [ 'href', 'name', 'target', 'aria-hidden', 'rel' ],
    del: ['cite', 'datetime'],
    iframe: ['src', 'frameborder', 'allowfullscreen'],
    img: [ 'src', 'width', 'height' ],
    input: ['checked', 'class', 'disabled', 'type'],
    ins: ['cite', 'datetime'],
    meta: ['name', 'content'],
    td: ['colspan', 'rowspan'],
    th: ['colspan', 'rowspan'],
    path: ['d'],
    svg: ['aria-hidden', 'height', 'version', 'viewbox', 'width'],
  },

  // *** The following is copied from sanitize-html's default options ***
  // Lots of these won't come up by default because we don't allow them
  selfClosing: [ 'img', 'br', 'hr', 'area', 'base', 'basefont', 'input', 'link', 'meta' ],
  // URL schemes we permit
  allowedSchemes: [ 'http', 'https', 'ftp', 'mailto' ],
  allowedSchemesByTag: {},
  allowedSchemesAppliedToAttributes: [ 'href', 'src', 'cite' ],
  allowProtocolRelative: true,
};
